services:
  db:
    image: postgres:15
    container_name: evently-db
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: PanPostGres1245
      POSTGRES_DB: evently_event
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "sa"]
      interval: 5s
      timeout: 3s
      retries: 5

  evently:
    build:
      context: .
      dockerfile: service/booking/Dockerfile
    container_name: evently-event
    depends_on:
      db:
        condition: service_healthy  # ✅ wait for DB
    env_file:
      - service/booking/.env
    ports:
      - "8081:8081"

volumes:
  pgdata: